// stores/counter.ts
import { defineStore } from 'pinia'
import productImage1 from '@/assets/images/product-1.png'
import productImage2 from '@/assets/images/product-2.png'
import productImage3 from '@/assets/images/product-3.png'
import productImage4 from '@/assets/images/product-4.png'
import productImage5 from '@/assets/images/product-5.png'
import productImage6 from '@/assets/images/product-6.png'
import productImage7 from '@/assets/images/product-7.png'
import productImage8 from '@/assets/images/product-8.png'
import pageImage1 from '@/assets/images/product-page-image-1.png'
import pageImage2 from '@/assets/images/product-page-image-2.png'
import pageImage3 from '@/assets/images/product-page-image-3.png'
import pageImage4 from '@/assets/images/product-page-image-4.png'
import pageImage5 from '@/assets/images/product-page-image-5.png'

export const useDataStore = defineStore('data', {
  state: () => ({
    productItems: [
        {
            id: '1',
            name: 'STREETWEAR BOX',
            gender: 'Mens',
            price: '400',
            guaranteedValue: '$300 - $500',
            contains: '2 - 3',
            featuring: 'off white, palm angels , amiri and heron preston',
            image: productImage1,
            desciption: "The £299 Mystery Box ensures a minimum value of over £500 and includes a variety of items, including Hoodies, T-Shirts, Sweatpants, and accessories. Wardrobe staples, you can't go wrong.",
            pageImage1: pageImage1,
            pageImage2: pageImage2,
            pageImage3: pageImage3,
            pageImage4: pageImage4,
            pageImage5: pageImage5,
        },
        {
            id: '2',
            name: 'STREETWEAR BOX',
            gender: 'Mens',
            price: '400',
            guaranteedValue: '$300 - $500',
            contains: '2 - 3',
            featuring: 'off white, palm angels , amiri and heron preston',
            image: productImage2,
            desciption: "The £299 Mystery Box ensures a minimum value of over £500 and includes a variety of items, including Hoodies, T-Shirts, Sweatpants, and accessories. Wardrobe staples, you can't go wrong.",
            pageImage1: pageImage1,
            pageImage2: pageImage2,
            pageImage3: pageImage3,
            pageImage4: pageImage4,
            pageImage5: pageImage5,
        },
        {
            id: '3',
            name: 'STREETWEAR BOX',
            gender: 'Mens',
            price: '400',
            guaranteedValue: '$300 - $500',
            contains: '2 - 3',
            featuring: 'off white, palm angels , amiri and heron preston',
            image: productImage3,
            desciption: "The £299 Mystery Box ensures a minimum value of over £500 and includes a variety of items, including Hoodies, T-Shirts, Sweatpants, and accessories. Wardrobe staples, you can't go wrong.",
            pageImage1: pageImage1,
            pageImage2: pageImage2,
            pageImage3: pageImage3,
            pageImage4: pageImage4,
            pageImage5: pageImage5,
        },
        {
            id: '4',
            name: 'STREETWEAR BOX',
            gender: 'Mens',
            price: '400',
            guaranteedValue: '$300 - $500',
            contains: '2 - 3',
            featuring: 'off white, palm angels , amiri and heron preston',
            image: productImage4,
            desciption: "The £299 Mystery Box ensures a minimum value of over £500 and includes a variety of items, including Hoodies, T-Shirts, Sweatpants, and accessories. Wardrobe staples, you can't go wrong.",
            pageImage1: pageImage1,
            pageImage2: pageImage2,
            pageImage3: pageImage3,
            pageImage4: pageImage4,
            pageImage5: pageImage5,
        },
        {
            id: '5',
            name: 'STREETWEAR BOX',
            gender: 'Mens',
            price: '400',
            guaranteedValue: '$300 - $500',
            contains: '2 - 3',
            featuring: 'off white, palm angels , amiri and heron preston',
            image: productImage5,
            desciption: "The £299 Mystery Box ensures a minimum value of over £500 and includes a variety of items, including Hoodies, T-Shirts, Sweatpants, and accessories. Wardrobe staples, you can't go wrong.",
            pageImage1: pageImage1,
            pageImage2: pageImage2,
            pageImage3: pageImage3,
            pageImage4: pageImage4,
            pageImage5: pageImage5,
        },
        {
            id: '6',
            name: 'STREETWEAR BOX',
            gender: 'Mens',
            price: '400',
            guaranteedValue: '$300 - $500',
            contains: '2 - 3',
            featuring: 'off white, palm angels , amiri and heron preston',
            image: productImage6,
            desciption: "The £299 Mystery Box ensures a minimum value of over £500 and includes a variety of items, including Hoodies, T-Shirts, Sweatpants, and accessories. Wardrobe staples, you can't go wrong.",
            pageImage1: pageImage1,
            pageImage2: pageImage2,
            pageImage3: pageImage3,
            pageImage4: pageImage4,
            pageImage5: pageImage5,
        },
        {
            id: '7',
            name: 'STREETWEAR BOX',
            gender: 'Mens',
            price: '400',
            guaranteedValue: '$300 - $500',
            contains: '2 - 3',
            featuring: 'off white, palm angels , amiri and heron preston',
            image: productImage7,
            desciption: "The £299 Mystery Box ensures a minimum value of over £500 and includes a variety of items, including Hoodies, T-Shirts, Sweatpants, and accessories. Wardrobe staples, you can't go wrong.",
            pageImage1: pageImage1,
            pageImage2: pageImage2,
            pageImage3: pageImage3,
            pageImage4: pageImage4,
            pageImage5: pageImage5,
        },
        {
            id: '8',
            name: 'STREETWEAR BOX',
            gender: 'Mens',
            price: '400',
            guaranteedValue: '$300 - $500',
            contains: '2 - 3',
            featuring: 'off white, palm angels , amiri and heron preston',
            image: productImage8,
            desciption: "The £299 Mystery Box ensures a minimum value of over £500 and includes a variety of items, including Hoodies, T-Shirts, Sweatpants, and accessories. Wardrobe staples, you can't go wrong.",
            pageImage1: pageImage1,
            pageImage2: pageImage2,
            pageImage3: pageImage3,
            pageImage4: pageImage4,
            pageImage5: pageImage5,
        },
        {
            id: '9',
            name: 'STREETWEAR BOX',
            gender: 'Mens',
            price: '400',
            guaranteedValue: '$300 - $500',
            contains: '2 - 3',
            featuring: 'off white, palm angels , amiri and heron preston',
            image: productImage5,
            desciption: "The £299 Mystery Box ensures a minimum value of over £500 and includes a variety of items, including Hoodies, T-Shirts, Sweatpants, and accessories. Wardrobe staples, you can't go wrong.",
            pageImage1: pageImage1,
            pageImage2: pageImage2,
            pageImage3: pageImage3,
            pageImage4: pageImage4,
            pageImage5: pageImage5,
        },
        {
            id: '10',
            name: 'STREETWEAR BOX',
            gender: 'Mens',
            price: '400',
            guaranteedValue: '$300 - $500',
            contains: '2 - 3',
            featuring: 'off white, palm angels , amiri and heron preston',
            image: productImage6,
            desciption: "The £299 Mystery Box ensures a minimum value of over £500 and includes a variety of items, including Hoodies, T-Shirts, Sweatpants, and accessories. Wardrobe staples, you can't go wrong.",
            pageImage1: pageImage1,
            pageImage2: pageImage2,
            pageImage3: pageImage3,
            pageImage4: pageImage4,
            pageImage5: pageImage5,
        },
        {
            id: '11',
            name: 'STREETWEAR BOX',
            gender: 'Mens',
            price: '400',
            guaranteedValue: '$300 - $500',
            contains: '2 - 3',
            featuring: 'off white, palm angels , amiri and heron preston',
            image: productImage7,
            desciption: "The £299 Mystery Box ensures a minimum value of over £500 and includes a variety of items, including Hoodies, T-Shirts, Sweatpants, and accessories. Wardrobe staples, you can't go wrong.",
            pageImage1: pageImage1,
            pageImage2: pageImage2,
            pageImage3: pageImage3,
            pageImage4: pageImage4,
            pageImage5: pageImage5,
        },
        {
            id: '12',
            name: 'STREETWEAR BOX',
            gender: 'Mens',
            price: '400',
            guaranteedValue: '$300 - $500',
            contains: '2 - 3',
            featuring: 'off white, palm angels , amiri and heron preston',
            image: productImage8,
            desciption: "The £299 Mystery Box ensures a minimum value of over £500 and includes a variety of items, including Hoodies, T-Shirts, Sweatpants, and accessories. Wardrobe staples, you can't go wrong.",
            pageImage1: pageImage1,
            pageImage2: pageImage2,
            pageImage3: pageImage3,
            pageImage4: pageImage4,
            pageImage5: pageImage5,
        },
    ],
  }),
  actions: {
    increment() {
      return
    },
  },
})
